module.exports = {
    mySidebar: [
        {
            type: 'category',
            label: 'BASICS',
            items: [
                {
                    type: 'doc',
                    id: 'basics/get_started'
                },
                // {
                //     type: 'doc',
                //     id: 'basics/authentication'
                // },
                // {
                //     type: 'doc',
                //     id: 'basics/calls'
                // },
            ],
        },
        // {
        //     type: 'category',
        //     label: 'CALL TYPES',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'call_types',
        //         },
        //     ],
        // },
        // {
        //     type: 'category',
        //     label: 'MODERATION',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'moderation',
        //         },
        //     ],
        // },
        // {
        //     type: 'category',
        //     label: 'RECORDING',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'recording',
        //         },
        //     ],
        // },
        // {
        //     type: 'category',
        //     label: 'STREAMING',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'streaming',
        //         },
        //     ],
        // },
        // {
        //     type: 'category',
        //     label: 'WEBHOOKS',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'webhooks',
        //         },
        //     ],
        // },

    ],
};