module.exports = {
    mySidebar: [
        {
            type: 'category',
            label: 'Basics',
            items: [
                {
                    type: 'doc',
                    id: 'basics/get_started'
                },
                // {
                //     type: 'doc',
                //     id: 'basics/authentication'
                // },
                // {
                //     type: 'doc',
                //     id: 'basics/calls'
                // },
            ],
        },
        // {
        //     type: 'category',
        //     label: 'Call types',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'call_types',
        //         },
        //     ],
        // },
        // {
        //     type: 'category',
        //     label: 'Moderation',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'moderation',
        //         },
        //     ],
        // },
        // {
        //     type: 'category',
        //     label: 'Recording',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'recording',
        //         },
        //     ],
        // },
        // {
        //     type: 'category',
        //     label: 'Streaming',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'streaming',
        //         },
        //     ],
        // },
        // {
        //     type: 'category',
        //     label: 'Webhooks',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'webhooks',
        //         },
        //     ],
        // },

    ],
};