fileNameModifier: snakeCase
fileExtension: .py
copyAdditionalFiles:
  - base_client.py
  - generic.py
  - stream_response.py
  - rate_limit.py
  - __init__.py
generateRequestTypes: false
modelsSubpackage: models
modelsCopyFiles: 
  - models/__init__.py
additionalParameters:
  clientClassName: VideoClient
  modelImportPrefix: getstream.