fileNameModifier: snakeCase
fileExtension: .py
explodeRequestIntoArgs: true
copyAdditionalFiles:
  - sync/base.py
  - generic.py
  - stream_response.py
  - rate_limit.py
  - __init__.py
clientOutputDirectory: video/sync/
generateRequestTypes: false
modelsSubpackage: models
modelsCopyFiles:
  - models/__init__.py
additionalParameters:
  clientClassName: VideoClient
  modelImportPrefix: getstream.