name: Dart Video Proto

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - name: Compile definitions
        run: docker run -it -e LANGUAGE=dart -e FOLDER=/local/dart-sdk -v $(pwd):/local ghcr.io/getstream/protocol:latest
