name: Dart Video Proto

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Dart
        uses: - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: ./install.sh
      - name: Compile definitions
        run: ./generate.sh dart
