name: Publish Docusaurus

on:
  push:
    paths:
      - 'docusaurus/video/docusaurus/**'
      - '.github/workflows/docusaurus-deploy.yml'

jobs:
  push_docusaurus:
    name: Publish docusaurus docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node 18
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 18
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: ${{ github.ref == 'refs/heads/main' && 'main' || 'staging' }}
          cli-target-branch: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
          destination-repository-name: 'stream-video-docusaurus'
          source-directory: 'docusaurus/video/docusaurus'
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
