name: Swift Video Proto

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sersoft-gmbh/swifty-linux-action@v1
        with:
          release-version: 5.6.1
      - name: Install dependencies
        run: ./install.sh
      - name: Compile definitions
        run: ./generate.sh swift
