name: Swift Video Proto

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
      - name: Get swift version
        run: swift --version # Swift 5.7.3
      - name: Install dependencies
        run: ./install.sh
      - name: Compile definitions
        run: ./generate.sh swift
