name: TypeScript Video Proto

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - name: Compile definitions
        run: docker run -v $(pwd):/local ghcr.io/getstream/protocol ts /local/ts-sdk
